
arm_variant_type:  # [linux and aarch64]
  - sbsa           # [linux and aarch64]
  # arm-variant * tegra requires glibc version which is currently not available.
  # binary glibc 2.29.0 <= recipe glibc 2.28 $PREFIX/bin/nvcc
  # The binary is not compatible with the recipe's glibc pinning.
  # See https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#system-requirements
  # Enable this once glibc is available on the main channel.
  #- tegra          # [linux and aarch64]

c_compiler:                # [win]
  - vs2019                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]
