# c_compiler_version:        # [linux]
#   - 12                     # [linux]
# cxx_compiler_version:      # [linux]
#   - 12                     # [linux]
arm_variant_type:  # [aarch64]
  - sbsa           # [aarch64]
VCVER:
  - 14.2
VSYEAR:
  - 2019
VSVER:
  - 16
RUNTIME_VERSION:
  - 14.29.30139
CL_VERSION:
  - 19.27.29111
  
zip_keys:
  -
    - VCVER
    - VSYEAR
    - VSVER
    - RUNTIME_VERSION
    - CL_VERSION
