c_compiler_version:        # [linux]
  - 12                     # [linux]
cxx_compiler_version:      # [linux]
  - 12                     # [linux]
arm_variant_type:  # [aarch64]
  - sbsa           # [aarch64]
VCVER:
  - 14.3
  - 14.2
#  - 14.1
VSYEAR:
  - 2022
  - 2019
#  - 2017
VSVER:
  - 17
  - 16
#  - 15
RUNTIME_VERSION:
  - 14.36.32532
  - 14.29.30139
#  - 14.16.27033
CL_VERSION:
  - 19.37.32822
  - 19.29.30139
#  - 19.16.27033
  
zip_keys:
  -
    - VCVER
    - VSYEAR
    - VSVER
    - RUNTIME_VERSION
    - CL_VERSION
