# c_compiler_version:        # [linux]
#   - 12                     # [linux]
# cxx_compiler_version:      # [linux]
#   - 12                     # [linux]
arm_variant_type:  # [aarch64]
  - sbsa           # [aarch64]
VCVER:
  - 14.2
VSYEAR:
  - 2019
CL_VERSION:
  - 19.27.29111
  
zip_keys:
  -
    - VCVER
    - VSYEAR
    - CL_VERSION
conda_glibc_ver:
  - 2.17          # [not aarch64]
  - 2.26          # [aarch64]