c_compiler_version:        # [linux]
  - 12                     # [linux]
cxx_compiler_version:      # [linux]
  - 12                     # [linux]
arm_variant_type:  # [aarch64]
  - sbsa           # [aarch64]
VSYEAR:
  - 2019
VSVER:
  - 16
CL_VERSION:
  - 19.29.30139
  
zip_keys:
  -
    - VCVER
    - VSYEAR
    - CL_VERSION
