c_compiler_version:        # [linux]
  - 12                     # [linux]
cxx_compiler_version:      # [linux]
  - 12                     # [linux]
arm_variant_type:  # [aarch64]
  - sbsa           # [aarch64]
  - tegra          # [aarch64]
VCVER:
  - 14.2
VSYEAR:
  - 2019
CL_VERSION:
  - 19.29.30139

zip_keys:
  -
    - VCVER
    - VSYEAR
    - CL_VERSION
  - # [aarch64]
    - arm_variant_type # [aarch64]
    - c_stdlib_version # [aarch64]

# For some reason, the minimum glibc version for tegra is much higher than sbsa
c_stdlib_version:  # [aarch64]
  - "2.17"  # [aarch64]
  - "2.34"  # [aarch64]
