# c_compiler_version:        # [linux]
#   - 12                     # [linux]
# cxx_compiler_version:      # [linux]
#   - 12                     # [linux]

arm_variant_type:  # [linux and aarch64]
  - sbsa           # [linux and aarch64]
  # arm-variant * tegra requires glibc version which is currently not available.
  # binary glibc 2.29.0 <= recipe glibc 2.28 $PREFIX/bin/nvcc
  # The binary is not compatible with the recipe's glibc pinning.
  # See https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#system-requirements
  # Enable this once glibc is available on the main channel.
  #- tegra          # [linux and aarch64]

VCVER:                     # [win]
  - 14.2                   # [win]
VSYEAR:                    # [win]
  - 2019                   # [win]
CL_VERSION:                # [win]
  - 19.29.30159            # [win]
c_compiler:                # [win]
  - vs2019                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]

zip_keys:
  -                        # [win]
    - VCVER                # [win]
    - VSYEAR               # [win]
    - CL_VERSION           # [win]
  # -                     # [linux and aarch64]
  #   - arm_variant_type  # [linux and aarch64]
    # - c_stdlib_version  # [linux and aarch64]
